name: "🤖 Chat Bot"

on:
  issues:
    types: [labeled, commented]
  issue_comment:
    types: [created]

jobs:
  handle-chat:
    if: >
      (github.event.label.name == 'chat' || contains(github.event.issue.labels.*.name, 'chat')) &&
      github.event.sender.login != 'PR-Pilot-AI'
    runs-on: ubuntu-latest
    steps:
      - name: AI Chat Response
        uses: PR-Pilot-AI/smart-actions/quick-task@v1
        with:
          api-key: ${{ secrets.PR_PILOT_API_KEY }}
          agent-instructions: |
              1. Read the content of issue #${{ github.event.issue.number }}.
              2. Comment on the issue, providing a response to the latest comment
