name: "🛠️ Generate Tool"

on:
  workflow_dispatch:
    inputs:
      tool-name:
        description: 'Name of the tool'
        required: true
      tool-inputs:
        description: 'Inputs required for the tool'
        required: true
      agent-instructions:
        description: 'Step-by-step instructions for the AI agent to create and use the tool'
        required: true

jobs:
  automate-tool-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Automate Tool Creation
        uses: PR-Pilot-AI/smart-actions/quick-task@v1
        with:
          api-key: ${{ secrets.PR_PILOT_API_KEY }}
          agent-instructions: |
            1. Access the Github repository and navigate to the specified directory for tool creation.
            2. Use the inputs provided: 
               - Tool Name: ${{ github.event.inputs.tool-name }}
               - Tool Inputs: ${{ github.event.inputs.tool-inputs }}
               - Agent Instructions: ${{ github.event.inputs.agent-instructions }}
            3. Follow the step-by-step instructions to create the tool as specified.
            4. Test the tool to ensure it works as expected.
            5. Create a Github issue summarizing the creation and testing of the tool, including any relevant details or challenges encountered.
